name: release-go
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: go-build
          path: ./build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}




