name: release-go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v -o build/maagot-jwt ./...

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-build
          path: ./build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/maagot-jwt
          asset_name: maagot-jwt
          asset_content_type: application/octet-stream
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
